### ISSUE TITLE
SCO_L and SCO_U missing lat,lon,alt

### ISSUE THREAD

**Issue by patrickjwright** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#126]
`AWS_latest_locations.csv` (on THREDDS and Dataverse) appears as:

```
SCO_L,2023-11-14 00:00:00,,,
SCO_U,2023-11-14 00:00:00,,,
```

**Comment by jasonebox** [comment]
indeed, had this issue and obtained the latest valid monthly average, latest OK monthly average (from my code) July 2017.
SCO_L 2017 Jul 72.2224 -26.8181 459±4 m
plots below, situation at SCO_U seems worse with no data since 2012?!
SCO_U 2012 Aug 72.3940 -27.2525 976±0 m
![image](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/32133350/6553c363-4b52-4223-b74a-dd25c8e9a5a0)

![image](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/32133350/9eb0d70b-03fd-44b2-af3d-2b3041cc172a)

**Comment by BaptisteVandecrux** [comment]
This is a known issue documented here: https://github.com/GEUS-Glaciology-and-Climate/pypromice/issues/173
This is due to:
- SCO_U and SCO_L GPS not working for many years.
- AWS_latest_positions.csv is generated by get_bufr function only seeing the tx data
- Since no tx data is available to make a regression, no latest position can be estimated.

I gave some ideas of how to solve it under the pypromice issue. It's coming up slowly on the to-do list.

**Comment by patrickjwright** [comment]
Thanks @BaptisteVandecrux and sorry for the repeat issue! As the Synoptic ingest is only focused on near real time data, it is OK to disclude these stations.

**Comment by BaptisteVandecrux** [comment]
Inter/extrapolated coordinates are now provided in data files as 'lat', 'lon' and 'alt'. 

The latest coordinates in the 'AWS_stations_metadata.csv' and 'AWS_sites_metadata.csv' are using this interpolation and therefore should not have any missing coordinates. 'AWS_latest_postions.csv' is discontinued. 

This started this summer on thedds and now in dataverse release V20 https://doi.org/10.22008/FK2/IW73UU.
