### ISSUE TITLE
KAN_B position

### ISSUE THREAD

**Issue by jasonebox** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#148]
re: dataverse data, via ECMWF Simon Noone <Simon.Noone@mu.ie> asks 

"Here is an example that I found of a station with no gps information at all. "

whereas the other stations include position data. I think it's worth including that position... what I have: 67.1252, -50.1832, 350 m

Jason

**Comment by BaptisteVandecrux** [comment]
Similar to #152, there is no GPS observations and there is a need to decide whether we fill a field called "gps_lon" with a value that is not measured continuously by a GPS.
On the dataverse, there is a [metadata file](https://dataverse.geus.dk/file.xhtml?persistentId=doi:10.22008/FK2/IW73UU/0RH4WD) that should have a set of "standard coordinates" for each station. The same standard, static coordinates should also be available as an attribute "lat" "lon" and "alt" in the netcdf files.

@sjnoone I suggest that you use the metadata file above and 
1) if `location_type` is `local glacier` or `ice sheet` then you use the observed coordinates,
2) if `location_type` is `tundra` or `bedrock` and there is no observed coordinates, then the standard static coordinates can be used instead

**Comment by BaptisteVandecrux** [comment]
Closing here because it is not a data-related issue.
I don't think the variable `gps_lat gps_lon gps_alt` should contain other thing that continuous GPS measurements.
We could decide to replace them with more general `lat lon alt` which would contain either interpolated or static values.
Coordinates interpolation was requested here: https://github.com/GEUS-Glaciology-and-Climate/pypromice/issues/236
and I am adding cases of static AWS there as well
