### ISSUE TITLE
QAS_L position: elevation of 1 in 2009

### ISSUE THREAD

**Issue by sjnoone** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#151]
## Note

The *QAS_L_hour*, *2009*, shows an altitude value of 1 for most of 2009.

see plot 
![QAS_L_hour_cleaned_plots](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/28791613/1fbf075f-062d-452d-87bd-5141b07a399a)

**Comment by BaptisteVandecrux** [comment]
Hi Simon,

Thanks for reporting this issue.

I implemented some filters that removed the erroneous data:
![image](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/5eced769-4b7d-48b8-a9a2-17287914e4da)

I can confirm that the jump in lat-lon in 2009 is due to the station being moved 1.6 km upstream, out of a crevasse field where it had been advected. 

I'll go through the other errors you reported and make a new release on the dataverse.

**Comment by sjnoone** [comment]
Hi Baptiste,

Thanks for addressing these issues so quickly. When will the updated data be released?
Simon

**Comment by BaptisteVandecrux** [comment]
Largest outlier removed and data release in V17 on the dataverse:
Remaining visible outliers should be easily removed by a rolling median or loess filter

![image](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/c810652e-e997-4a4a-967e-3675ffdd52e0)
