### ISSUE TITLE
NUK_K: Wind speed at zero during winter 2015-2016

### ISSUE THREAD

**Issue by mankoff** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#19]
Taken from https://github.com/GEUS-Glaciology-and-Climate/pypromice/issues/39

Could be removed by a "frozen anemometer" filter
![image](https://user-images.githubusercontent.com/35140661/100874136-6b098900-34a4-11eb-99f4-7d356ee19ccf.png)

**Comment by patrickjwright** [comment]
Great case for a "persistence" flag as well.

**Comment by mankoff** [comment]
What does `persistence` mean? We have years, and we have https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/ALL_TIME

**Comment by mankoff** [comment]
I'm curious what closing this means. No message/info about the resolution. Has the circled area been flagged? Is wind direction still valid even if no speed? Why are the blue dots in this graphic flagged bad?

**Comment by BaptisteVandecrux** [comment]
It is true that closing an issue deserves more info.

The low-wind-speed period was removed:
![20230819_071842.jpg](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/6c87a772-1d80-41c0-99e9-82c5f50f237f)

using the following flag:
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/blob/669e14dbfecf968365bb3bbf0730b49db87415a2/flags/NUK_K.csv?plain=1#L3

As specified in the flag file, I (quickly) checked the data and did not find other sensors affected neither found evidence of station collapse or burial. Still possible that I missed something or got the start/end date wrong. So the issue is closed (to declutter our to-do list ) but still findable and open for comments.

The other blue period showed in the comment above was probably a mistake and is not flagged anymore.

An automatic flagging routine will help not sending the first data points to WMO, but will miss periods when the sensor is slowed down by rime or is allowed to spin for few hours before being blocked again. So I believe that an expert assessment of what went wrong and whether other instruments were impacted is necessary.

Glad that someone is following along and it's not just me playing with the data!

**Comment by mankoff** [comment]
On 2023-08-19 at 03:38 -02, Baptiste Vandecrux ***@***.***> wrote...
> It is true that closing an issue deserves more info.

Yes. Every closed issue should have a comment. Either a tag (e.g. "duplicate") or some info. Often all that is needed the commit message "Closes #xx", or even just this one line:

> using the following flag:
> https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/blob/669e14dbfecf968365bb3bbf0730b49db87415a2/flags/NUK_K.csv?plain=1#L3
