### ISSUE TITLE
KPC_Uv3 level 3 file starts in 2056

### ISSUE THREAD

**Issue by BaptisteVandecrux** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#22]
![image](https://user-images.githubusercontent.com/35140661/211277363-3c309bb8-fe17-4c49-972e-c20740ee9d45.png)

**Comment by patrickjwright** [comment]
Duplicate of https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/issues/12

**Comment by patrickjwright** [comment]
One possible solution (until the logger actually gets re-synchronized on a field visit), is to check for future years, then reset the data only for `KPC_Uv3` to start in 2022. For BUFR processing and submission to WMO we are currently ignoring this station and using `KPC_U` instead. So, I'm not sure there is a really a priority to stub in a manual fix for this in the processing code (which would then just have to be removed later)? Instead, we need to prioritize a fix on this logger during the next field visit.

**Comment by BaptisteVandecrux** [comment]
Sorry for missing the other issue.
Station was installed on 2022-05-28.

**Comment by BaptisteVandecrux** [comment]
There was the same problem at SDL and penny actually modified the raw file in the L0 folder:
![image](https://user-images.githubusercontent.com/35140661/211285077-6598fd11-af7d-4118-99ae-98ca0c5dada4.png)

and the toml file:
![image](https://user-images.githubusercontent.com/35140661/211285134-eadc6a50-c26e-4aad-b99e-938913ad7055.png)

As a quick fix I am ok with this procedure.

In the future, it would be great to have it as a part of the L3 data processing.
A modified file is not L0 any more.

It's easy to know on which day the file should start but what about the hour?
At the moment, modifying the raw file is not transparent for what shift was applied and how it was motivated.

@PennyHow did you have some thoughts on this when you fixed SDL?

**Comment by PennyHow** [comment]
Full documentation of this fix is on our `aws-l0` gitlab repo, including how we pinpointed the hour of the first reading. It is good practise to document it here also on our public forum, so I will put it below.

We could have a `time_fix` variable in the `SDL.toml` config file (and others where this problem exists), which states the correct time that the time-series starts from? My only reservation is that this is quite a specific problem and so I don't know if it needs full integration into `pypromice.` 

As for the file modification, the original `L0` file still exists in the Gitlab repo, it just is not called in the processing. So we never overwrite anything entirely, and the justification for the modification is documented. I see this is as a modified `L0` file, as the original file is unusable for processing (at least in the current `pypromice` processing or any preceding workflow). Without the modification, it could not be included in the `L3` data product.

**Comment by PennyHow** [comment]
Summarised from Gitlab `aws-l0` [issue 6](https://geusgitlab.geus.dk/glaciology-and-climate/promice/aws-l0/-/issues/6), which could potentially be adapted to correct KPC_Uv3 timestamps.


Correct timestamps for the `SDL` `L0 RAW` file. A copy of the original file is now at `raw/SDL/archive/SDL_2022_raw.txt`, and the corrected version can be found at `raw/SDL/SDL_2022_raw_corrected.txt`. 

The `rec` variable, along with the Datalogger clock (`25/01/1988 03.34.48`, as BAP wrote previously) should typically be used to correct the time, as each `rec` entry should be relative to the Datalogger clock. However, the problem here is that the first `rec` entry is `0` and the first datetime entry is `2123-02-21 18:08:16`; so `rec` does not follow the Datalogger clock.

As a result, some detective work had to be done to decipher a time correction...

- From the maintenance sheet from the 2021 station visit, the station was set-up on 14/06/2021 at roughly 15.00 (unfortunately there is no futher information to better define the time window of the station visit)
- From the 2022 visit documentation, the station was visited on 23/06/2022. Screen grabs from the LoggerNet program indicate that the old program was checked at 13.58 and the new logger program was installed by 14.48. 

Further evidence from the first `L0 tx` message verifies this. We (myself and @robertfausto) looked at the first transmission from `SDL` (imei modem identifier provided on Gitlab repo issue) to figure out the first logged data entry: 

```
MOMSN: 6
MTMSN: 0
Time of Session (UTC): Mon Jun 14 18:22:14 2021
Session Status: 00 - Transfer OK
Message Size (bytes): 105

Unit Location: Lat = 66.01649 Long = -44.31423
CEPradius = 9
```

**So, it is assumed the first data was logged on 14/06/2021 at 18:22.**

Here is how the time shift was performed on the `L0 RAW` file:

```
from datetime import datetime, timedelta

# Open raw file to read from
with open ('SDL_2022_raw.txt', "r") as myfile:
    data = myfile.read().splitlines()

# Parse datetime strings from lines (disregarding header lines and erroneous entries)
all_data = data[6:]
d_str = [d.split('"')[1] for d in all_data]
    
# Convert to datetime objects
date0 = [datetime.strptime(d, '%Y-%m-%d %H:%M:%S') for d in d_str]

# Find time shift between first entry and expected datetime
s = date0[0] - datetime(2021,6,14,18,22,0)

# Adjust all entries based on time shift
date1 = [d-s for d in date0]
    
# Open raw_corrected file to write to
with open ('SDL_2022_raw_corrected.txt', "w") as myfile:
    
    # Write header lines
    for d in data[:4]:
        myfile.write(d + '\n')
    
    # Write data entries, replacing datetimes with shifted datetimes
    for d in range(len(all_data)):
        s = all_data[d].replace(d_str[d], date1[d].strftime('%Y-%m-%d %H:%M:%S'))
        myfile.write(s + '\n')
```

So the hourly `SDL Level_3` product now looks like this now:

```
| time                | p_u      | p_l      | t_u      | t_l      | rh_u    | ...      |
|---------------------|----------|----------|----------|----------|---------|----------|
| 2021-06-14 19:00:00 | 745.2833 | 745.4667 | -8.52    | -8.32    | 59.2833 | ...      |
| 2021-06-14 20:00:00 | 745.0833 | 745.3    | -7.8167  | -7.9333  | 59.9    | ...      |
| 2021-06-14 21:00:00 | 744.9333 | 745.1833 | -9.0667  | -8.95    | 62.0833 | ...      |
| 2021-06-14 22:00:00 | 744.9667 | 745.2833 | -10.6833 | -10.5333 | 69.9167 | ...      |
| 2021-06-14 23:00:00 | 744.8667 | 745.3    | -11.6667 | -11.8    | 75.8333 | ...      |
| 2021-06-15 00:00:00 | 744.7    | 745.25   | -13.1167 | -13.5667 | 78.2333 | ...      |
| 2021-06-15 01:00:00 | 744.55   | 745.1333 | -14.0667 | -14.6833 | 80.3833 | ...      |
| 2021-06-15 02:00:00 | 744.4    | 745.0833 | -15.5833 | -17.3667 | 84.45   | ...      |
| 2021-06-15 03:00:00 | 744.2833 | 745.2167 | -18.0833 | -20.5333 | 86.4333 | ...      |
| 2021-06-15 04:00:00 | 744.05   | 745.0333 | -18.5667 | -20.5833 | 82.3667 | ...      |
| 2021-06-15 05:00:00 | 743.8833 | 744.8833 | -18.95   | -20.3167 | 81.5    | ...      |
| 2021-06-15 06:00:00 | 743.95   | 744.9333 | -19.2    | -20.4    | 80.6333 | ...      |
| 2021-06-15 07:00:00 | 744.1833 | 745.1333 | -19.8333 | -19.8667 | 80.9167 | ...      |
| 2021-06-15 08:00:00 | 744.3833 | 745.1167 | -16.0833 | -16.0833 | 84.1667 | ...      |
```

**Comment by patrickjwright** [comment]
@PennyHow I am fine with using this similar approach to making an L0 corrected file for KPC_Uv3. I also agree it should not be a part of pypromice, since this is a station-specific problem (that hopefully will go away soon).

One question: your correction above appears to be for raw files, how do we handle the 2056 year in transmitted data?

**Comment by BaptisteVandecrux** [comment]
Thanks Penny!
I hadn't seen your reply on the GitLab issue.

I agree that it is the best we can do at the moment and that it could be repeated at KPC_Uv3.

In my opinion, a time shift is not much different than a rotated wind direction measurement or a taped sensor (#13): it needs to be corrected or removed before the data is used to produce the L3 data or before it is sent to WMO. See some details about flagging and adjusting the data on #13 .

**Comment by PennyHow** [comment]
> One question: your correction above appears to be for raw files, how do we handle the 2056 year in transmitted data?

Hmm. We don't handle this time shift in the `tx` data at the moment. This is a good point, along with @BaptisteVandecrux.

> In my opinion, a time shift is not much different than a rotated wind direction measurement or a taped sensor (https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/issues/13): it needs to be corrected or removed before the data is used to produce the L3 data or before it is sent to WMO.

A time shift variable and processing step may be necessary in `pypromice` as this is something that needs to work on an operational level. I'll open up a branch and migrate over the method stated above for fixing erroneous time stamps.

**Comment by mankoff** [comment]
Just here to repeat what Baptiste said. Not sure why this is considered special. Seems like a generic flag / fix scenario.

**Comment by PennyHow** [comment]
Noted. I forgot that this timestamp error was in the `L0 tx` as well as `L0 raw`. Given that we want near-real-time `tx` data that is correct, I see that this timestamp fix functionality needs to be integrated into `pypromice` with a flag in the `config` file. I'm working on it.

**Comment by PennyHow** [comment]
Coordinated with @BaptisteVandecrux that he will collate together the current fixing functionality and put it [here](https://github.com/GEUS-Glaciology-and-Climate/pypromice/tree/fixing-data). This is where the timestamp fixing will also be implemented, as part of the data fixing step (rather than through the station `config` `.toml` file).

**Comment by BaptisteVandecrux** [comment]
Found the appropriate time shift (-12361.4583 days) by comparing to the KPC_U station:
![image](https://user-images.githubusercontent.com/35140661/217275434-213a65a4-5438-4ed6-8a9b-01d29ec0d0dd.png)

Will be fixed in the next release of data.
This was done on hourly data and could be further refined using 10min values

**Comment by patrickjwright** [comment]
I can confirm that this is now fixed in both `aws-l3/tx` and `aws-l3/level_3`. I will change the WMO config to allow this station to flow to DMI. @PennyHow @BaptisteVandecrux should we close this issue?

If so, we can also close: https://geusgitlab.geus.dk/glaciology-and-climate/promice/aws-l0/-/issues/10

**Comment by BaptisteVandecrux** [comment]
I had a second look at the data and refined the time shift by 30min. I'd say that the shifted time stamps are accurate +/- 15 min. Can you ask what is the DMI requirement for time step accuracy? If more is needed I can go into the 10 min data.

I'm fine closing the issue if we reached a sufficient solution.

**Comment by BaptisteVandecrux** [comment]
Now released on the dataverse: https://doi.org/10.22008/FK2/IW73UU
