### ISSUE TITLE
Several issues in the coordinate file AWS_station_locations.csv

### ISSUE THREAD

**Issue by BaptisteVandecrux** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#31]
- [ ] Missing one/two boom info

- [ ] Missing location type (ice sheet, local glacier, tundra, not Greenland)

- [x] **ZAK_L** coordinate currently `74.379929,-7.428274,122.5` when they should be `74.625,-21.376,659.150` (I extracted this from one line in the file, maybe there's a better way to do it)

- [x] **ZAK_L** is very close from ZAK_U and at similar elevation compared to ZAK_Uv3 located 3km away. I just want to make sure there is not a problem in the naming of these three stations, or on the files that are being used.

- [x] Missing **TAS_U**, discontinued on 2015-08-13 but still part of the dataset, `65.6978,-38.8668,570`  (from last official PROMICE info sheet: PROMICE_coordinates_2015)

- [x] Missing **QAS_A**, discontinued on 2015-08-24 but still part of the dataset, `61.243,-46.7328,1000`  (from last official PROMICE info sheet: PROMICE_coordinates_2015)

- [x] Missing **NUK_N**, discontinued on 2014-07-25 but still part of the dataset, `64.9452,-49.885,920`  (from last official PROMICE info sheet: PROMICE_coordinates_2015)

- [x] Missing **KAN_B**, still active but not moving: `67.1252,-50.1832,350`  (from last official PROMICE info sheet: PROMICE_coordinates_2015)

- [x] QAS_Lv3 coordinate missing

**Comment by patrickjwright** [comment]
@BaptisteVandecrux I assume you are referring to this:
https://geusgitlab.geus.dk/glaciology-and-climate/promice/aws-l3/-/blob/main/AWS_station_locations.csv

A few notes:
This is meant to be positions only, so I'm not sure one/two boom or location type is needed here? I suppose it could be useful though.

This file is totally "data driven" from the transmitted position data. Also, positions are the most recent point from a 3-month linear trend (not the actual most recent transmitted position)... perhaps this could cause the difference you are seeing with `ZAK_L`?

If there is not recent data, I believe I go back and find any historical data to make the linear trend on. I will check the missing stations and report back.

Thanks!

**Comment by patrickjwright** [comment]
Posting these for reference.

Current `ZAK_L` elevation:
![image](https://user-images.githubusercontent.com/10144675/222107082-b4770191-af09-40c0-8d5c-b461e0bd1406.png)

Latitude:
![image](https://user-images.githubusercontent.com/10144675/222107172-66994022-e100-4966-8730-24fafa836bb7.png)

Longitude:
![image](https://user-images.githubusercontent.com/10144675/222107278-82b53a43-8b27-4da5-9817-20583e609cdc.png)

**Comment by patrickjwright** [comment]
`ZAK_L` had errors in the tx toml file, resulting in reading of incorrect fields for GPS coordinates. This has been fixed [here](https://geusgitlab.geus.dk/glaciology-and-climate/promice/aws-l0/-/commit/9da6454116734adb318e28de74f2abd92052bd04).

**Comment by patrickjwright** [comment]
`ZAK_L` now corrected:
https://geusgitlab.geus.dk/glaciology-and-climate/promice/aws-l3/-/commit/246a645ec05d5a6b5c15a3aca5b335e5084a9364

![image](https://user-images.githubusercontent.com/10144675/222438710-7d936e6a-e878-4deb-b4d8-7a0447a0122c.png)

**Comment by patrickjwright** [comment]
`TAS_U`, `QAS_A`, `NUK_N` and `KAN_B` now have entries in a new config dict, `wmo_config.positions_seed`. This can be used to "seed" the locations file with any stations that have been discontinued. In addition, `KAN_B` is somewhat unique in that it is transmitting, but not transmitting position data. For stations like this, I have added a set called `wmo_config.positions_update_timestamp_only`, which will update the timestamp, but otherwise use the "seeded" position.

For QAS_Lv3, there are problems with the station using a non-standard logger program which is preventing transmission of valid data. @robertfausto says it needs to be addressed in the field. Therefore, I am not treating this station here. When the station gets a correct logger program and correct sensors, it will flow normally into the `AWS_station_locations.csv` file.

For now, I am not including any information about one-boom or two-boom or location type, and just keeping this file to position and associated timestamp metadata only.

This can be closed with the merging of https://github.com/GEUS-Glaciology-and-Climate/pypromice/pull/107

Thanks for the review @BaptisteVandecrux!
