### ISSUE TITLE
L3 dataset should contain variable description

### ISSUE THREAD

**Issue by BaptisteVandecrux** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#33]
I suggest having a copy [variable.csv](https://github.com/GEUS-Glaciology-and-Climate/pypromice/blob/main/src/pypromice/variables.csv) in the level 3 dataset and on the dataverse. It's a necessary metadata to get along with the dataset.

**Comment by PennyHow** [comment]
A copy is on the Dataverse with the AWS datasets, named [AWS_variables.csv](https://doi.org/10.22008/FK2/IW73UU/J20XWS).

Where else do you think it should be? We don't keep it on the Gitlab Level 3 repo because there is a copy with `pypromice` and want to reduce duplicates.

Or are there specific descriptions of the variables that you would like adding to the variables.csv look-up table? We have some descriptions with the [AWS dataset readme](https://doi.org/10.22008/FK2/IW73UU/RHCSAC) which could be migrated over.

**Comment by BaptisteVandecrux** [comment]
Good that it is on the dataverse. 

I was looking at the Gitlab Level 3 repo. I think it should be wherever the csv files are found, since the csv header is not human readable (like what is z_pt_cor). But since Gitlab is for GEUS users it's not so critical.

Maybe it should also be on the THREDDS server, since the csv will be there as well.

**Comment by PennyHow** [comment]
I think putting it on the thredds server is a good idea. Maybe @patrickjwright, can you do this?

**Comment by patrickjwright** [comment]
Yes, I agree. I will get this file onto THREDDS.

**Comment by patrickjwright** [comment]
Both `AWS_station_locations.csv` and `AWS_variables.csv` are now in a dedicated `metadata` directory on THREDDS. They will be updated hourly with any changes.

https://thredds.geus.dk/thredds/catalog/metadata/catalog.html
